import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Local Aeonik Fonts
const aeonikBlack = localFont({
  src: "../public/fonts/Aeonik-Black.ttf",
  variable: "--font-aeonik-black",
});

const aeonikBold = localFont({
  src: "../public/fonts/Aeonik-Bold.ttf",
  variable: "--font-aeonik-bold",
});

const aeonikMedium = localFont({
  src: "../public/fonts/Aeonik-Medium.ttf",
  variable: "--font-aeonik-medium",
});

const aeonikRegular = localFont({
  src: "../public/fonts/Aeonik-Regular.ttf",
  variable: "--font-aeonik-regular",
});

const aeonikLight = localFont({
  src: "../public/fonts/Aeonik-Light.ttf",
  variable: "--font-aeonik-light",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${aeonikBlack.variable} ${aeonikBold.variable} ${aeonikMedium.variable} ${aeonikRegular.variable} ${aeonikLight.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
